version: 2

sources:
  - name: redcards_structured
    database: EDW_DEV
    schema: TEMP
    tables:
      - name: redcards_structured
        loaded_at_field: LASTUPDATED
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 5
            period: day
